name: 'codeql-summary-generator'
description: 'CodeQL Summary Generator'

inputs:
  projects:
    description: "Project File with projects"
    default: ./projects.json

  format:
    description: "Exporting Format (default: bundle)"
    default: bundle

  repository:
    description: "GitHub Repository"
    default: ${{ github.repository }}

  token:
    description: "GitHub Personal Access Token"
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Installing Dependencies"
        pushd ${{ github.action_path }}
        python3 -m pip install pipenv && python3 -m pipenv install --system
        popd
        echo "::endgroup::"

    # -i ./testing/codeql-bundle/projects.json -f bundle --working ./testing/codeql-bundle
    - shell: bash
      run: |
        PYTHONPATH=${{ github.action_path }} && export PYTHONPATH=${{ github.action_path }}
        python3 -m codeqlsummaries \
          --input "${{ inputs.projects }}" \
          --format "${{ inputs.format }}" \
          --github-token "${{ inputs.token }}" \
          --github-repository "${{ inputs.repository }}"

