name: 'codeql-summarize'
description: 'CodeQL Summarize Action'

inputs:
  project:
    description: "Project Repo (owner/name)"

  projects:
    description: "Project File with projects"
    default: ./projects.json

  language:
    description: "Project Language"

  format:
    description: "Exporting Format (default: bundle)"
    default: extensions

  output:
    description: "Output Directory"
    default: ./

  repository:
    description: "GitHub Repository"
    default: ${{ github.repository }}

  token:
    description: "GitHub Personal Access Token"
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - shell: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        "${{ github.action_path }}/codeql-summarize" \
          --input "${{ inputs.projects }}" \
          --output "${{ inputs.output }}" \
          --format "${{ inputs.format }}" \
          --project-repo "${{ inputs.project }}" \
          --language "${{ inputs.language }}" \
          --github-token "${{ inputs.token }}" \
          --github-repository "${{ inputs.repository }}"
