// This file is Automatically Generated based on the files in-side this relative
// directory. This makes it easier to automate this process.
import java

module geekmasherorg {
    private import geekmasherorg.java_summarize.EsapiEsapiJavaLegacyGenerated

}
