name: Python Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade black pyright

    - name: Run Tests
      run: |
        python -m unittest discover -v -s ./tests -p test_*.py

    - name: End-2-end Tests
      env:
        CODEQL_TOKEN: ${{ secrets.CODEQL_TOKEN }}
      run: |
        ./gh-codeql-summarize --github-token $CODEQL_TOKEN -i ./examples/projects.json -f bundle -o ./examples


    # Pull Request auto-linting
    - name: Lint
      if: github.event_name == 'pull_request'
      run: |
        black .
        
    - name: Linting Commit Update
      if: github.event_name == 'pull_request'
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto Linting Code using Black" && git push || echo "No changes to commit"
        
    
