name: Python Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run Tests
        run: |
          pipenv run tests

      - name: End-2-end Tests
        env:
          GITHUB_TOKEN: ${{ secrets.CODEQL_TOKEN }}
        run: |
          pipenv run main \
            -i ./examples/projects.json \
            -f bundle \
            -o ./examples \
            --disable-banner

      # Pull Request auto-linting
      - name: Lint
        if: github.event_name == 'pull_request'
        run: |
          pipenv run lint

      - name: Linting Commit Update
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto Linting Code using Black" && git push || echo "No changes to commit"
